Baslat: derle calistir
derle:
	g++ -I ./include -o ./lib/HeapTree.o -c ./src/HeapTree.cpp
	g++ -I ./include -o ./lib/islem.o -c ./src/islem.cpp
	g++ -I ./include -o ./lib/Sayi.o -c ./src/Sayi.cpp
	g++ -I ./include -o ./bin/odev ./lib/Sayi.o ./lib/islem.o ./lib/HeapTree.o ./src/main.cpp
calistir:
	./bin/odev	
	